### ISSUE TITLE
Please modify parsing for latest sg_edges_list format

### ISSUE THREAD

**Issue by pb-cdunn** [samarthrvittal/lookatgraphs#24]
Really, you don't need `csv.reader()` at all. Just use:

  rows = line.strip().split()

That will split on all whitespace, including tabs, and it will drop leading and trailing whitespace.

For reference: PacificBiosciences/FALCON-integrate#45

**Comment by md5sam** [comment]
Thanks for the heads-up, will fix this ASAP.

**Comment by md5sam** [comment]
Sorry for the delay - this is now fixed for parsing latest sg_edges_list format
