### ISSUE TITLE
Report overlap coverage in utils/graph_of_overlaps.sh

### ISSUE THREAD

**Issue by md5sam** [samarthrvittal/lookatgraphs#4]
It might be useful to report overlap coverage instead of the constant placeholder value. 

In the case of overlap FASTG, the sequence in each record represents the shared sequence between two overlapping reads. Knowing the coverage of this sequence, if a contig ends at one of these nodes, we could make a decision on why the assembler chose to cut the contig at this node.

**Comment by rchikhi** [comment]
#enhancement

**Comment by rchikhi** [comment]
probably could close this issue as i doubt you'll keep supporting graph_of_overlaps.sh
