### ISSUE TITLE
Remove double edges

### ISSUE THREAD

**Issue by rchikhi** [samarthrvittal/lookatgraphs#7]
I had a look at the test/ data. It feels too weird to have a graph with double edges there :)
Don't you think? 
We need to fix the double edges issue before release

**Comment by md5sam** [comment]
Agreed, I need to think more about how to resolve these double edges. If Falcon itself is reporting a double edge (by connecting B to B and E to E for every pair), then I need to think of maybe an alternative way of representing this (possibly redundant) information. 

Let's move the release to early next week ?

**Comment by rchikhi** [comment]
Yep lets see on monday.

**Comment by rchikhi** [comment]
Have a look at the small example, sg_edges_list:

000000001:B 000000000:B 000000000 4000 0 1000 100.0 G
000000002:B 000000001:B 000000001 3000 0 1000 100.0 G
000000000:E 000000001:E 000000001 1000 4000 1000 100.0 G
000000001:E 000000002:E 000000002 1000 3000 1000 100.0 G

**Comment by rchikhi** [comment]
Fixed as of today's patch
